worker_processes 1;
error_log /dev/stdout info;

events {
  worker_connections 1024;
}

rtmp {
  server {
    listen 1935;
    chunk_size 4096;

    application stream {
      live on;
      record off;
      push rtmp://ome:1935/app/key;
      push rtmp://127.0.0.1:1935/restream/input;
    }

    application restream {
      live on;
      record off;
    }
  }
}

http {
  server {
    listen 8080;

    location /healthz {
      return 200 "ok\n";
    }
  }
}
